-- ==============================================================================
-- SMART COLLEGE AI / DIGITAL TWIN OS — SUPABASE DATABASE SCHEMA & SEED DATA
-- Project: https://aqfqdjhddfvyprpwccyp.supabase.co
-- Generated for Smart College AI Management Platform
-- ==============================================================================

-- 1. DEPARTMENTS TABLE
CREATE TABLE IF NOT EXISTS public.departments (
    dept_code VARCHAR(10) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    building VARCHAR(100) NOT NULL,
    hod_name VARCHAR(100) NOT NULL
);

-- 2. STUDENTS TABLE (Matches Table 1 from User Prompt)
CREATE TABLE IF NOT EXISTS public.students (
    student_id VARCHAR(20) PRIMARY KEY,
    password VARCHAR(100) NOT NULL DEFAULT 'student@123',
    full_name VARCHAR(100) NOT NULL,
    department VARCHAR(10) NOT NULL REFERENCES public.departments(dept_code) ON DELETE CASCADE,
    email VARCHAR(150) NOT NULL UNIQUE,
    cgpa NUMERIC(4, 2) NOT NULL,
    phone VARCHAR(25) NOT NULL,
    semester INT NOT NULL DEFAULT 8,
    year INT NOT NULL DEFAULT 4,
    attendance_pct NUMERIC(5, 2) NOT NULL DEFAULT 87.4,
    fee_balance NUMERIC(10, 2) NOT NULL DEFAULT 12500.00,
    fee_status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    digital_twin_score INT NOT NULL DEFAULT 94,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. STAFF TABLE (Comprehensive Faculty & Admin Roster)
CREATE TABLE IF NOT EXISTS public.staff (
    staff_id VARCHAR(20) PRIMARY KEY,
    password VARCHAR(100) NOT NULL DEFAULT 'staff@123',
    full_name VARCHAR(100) NOT NULL,
    department VARCHAR(10) NOT NULL REFERENCES public.departments(dept_code) ON DELETE CASCADE,
    designation VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone VARCHAR(25) NOT NULL,
    cabin_location VARCHAR(100) NOT NULL,
    specialization VARCHAR(150) NOT NULL,
    experience_years INT NOT NULL DEFAULT 5,
    office_hours VARCHAR(150) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. SUBJECTS TABLE
CREATE TABLE IF NOT EXISTS public.subjects (
    subject_code VARCHAR(20) PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    department VARCHAR(10) NOT NULL REFERENCES public.departments(dept_code) ON DELETE CASCADE,
    semester INT NOT NULL,
    credits INT NOT NULL DEFAULT 4,
    faculty_id VARCHAR(20) REFERENCES public.staff(staff_id) ON DELETE SET NULL,
    faculty_name VARCHAR(100),
    room VARCHAR(50)
);

-- 5. STUDENT SUBJECT ATTENDANCE TABLE
CREATE TABLE IF NOT EXISTS public.student_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(20) NOT NULL REFERENCES public.students(student_id) ON DELETE CASCADE,
    subject_code VARCHAR(20) NOT NULL REFERENCES public.subjects(subject_code) ON DELETE CASCADE,
    subject_name VARCHAR(150) NOT NULL,
    attended_sessions INT NOT NULL,
    total_sessions INT NOT NULL,
    percentage NUMERIC(5, 2) NOT NULL,
    status VARCHAR(20) NOT NULL -- 'Good', 'Warning', 'Critical'
);

-- 6. FEE RECORDS TABLE
CREATE TABLE IF NOT EXISTS public.fee_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(20) NOT NULL REFERENCES public.students(student_id) ON DELETE CASCADE,
    semester INT NOT NULL,
    academic_year VARCHAR(20) NOT NULL DEFAULT '2025-2026',
    tuition_fee NUMERIC(10, 2) NOT NULL,
    lab_fee NUMERIC(10, 2) NOT NULL DEFAULT 5000.00,
    exam_fee NUMERIC(10, 2) NOT NULL DEFAULT 2500.00,
    paid_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    balance_amount NUMERIC(10, 2) NOT NULL,
    status VARCHAR(20) NOT NULL, -- 'Paid', 'Partial', 'Pending'
    due_date DATE NOT NULL
);

-- 7. CERTIFICATE & SERVICE REQUESTS TABLE
CREATE TABLE IF NOT EXISTS public.certificate_requests (
    request_id VARCHAR(50) PRIMARY KEY,
    student_id VARCHAR(20) NOT NULL REFERENCES public.students(student_id) ON DELETE CASCADE,
    student_name VARCHAR(100) NOT NULL,
    certificate_type VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'In Review', -- 'In Review', 'Approved', 'Rejected', 'Generated'
    applied_date DATE NOT NULL DEFAULT CURRENT_DATE,
    purpose VARCHAR(255),
    remarks VARCHAR(255)
);

-- 8. ACTIVITY LOGS TABLE
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(20) NOT NULL REFERENCES public.students(student_id) ON DELETE CASCADE,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    time_label VARCHAR(50) NOT NULL,
    icon VARCHAR(50) NOT NULL DEFAULT 'check_circle',
    icon_color VARCHAR(50) NOT NULL DEFAULT 'emerald'
);

-- 9. CHATBOT KNOWLEDGE BASE TABLE
CREATE TABLE IF NOT EXISTS public.knowledge_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    keywords TEXT[] NOT NULL
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Enable public read and write access for development & portal functionality
-- ==============================================================================
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fee_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificate_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_base ENABLE ROW LEVEL SECURITY;

-- Anonymous and authenticated access policies
CREATE POLICY "Allow public select all on departments" ON public.departments FOR SELECT USING (true);
CREATE POLICY "Allow public select all on students" ON public.students FOR SELECT USING (true);
CREATE POLICY "Allow public update students" ON public.students FOR UPDATE USING (true);
CREATE POLICY "Allow public select all on staff" ON public.staff FOR SELECT USING (true);
CREATE POLICY "Allow public select all on subjects" ON public.subjects FOR SELECT USING (true);
CREATE POLICY "Allow public select all on student_attendance" ON public.student_attendance FOR SELECT USING (true);
CREATE POLICY "Allow public select all on fee_records" ON public.fee_records FOR SELECT USING (true);
CREATE POLICY "Allow public update fee_records" ON public.fee_records FOR UPDATE USING (true);
CREATE POLICY "Allow public select all on certificate_requests" ON public.certificate_requests FOR SELECT USING (true);
CREATE POLICY "Allow public insert on certificate_requests" ON public.certificate_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on certificate_requests" ON public.certificate_requests FOR UPDATE USING (true);
CREATE POLICY "Allow public select all on activity_logs" ON public.activity_logs FOR SELECT USING (true);
CREATE POLICY "Allow public insert on activity_logs" ON public.activity_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select all on knowledge_base" ON public.knowledge_base FOR SELECT USING (true);

-- ==============================================================================
-- SEED DATA INSERTIONS
-- ==============================================================================

-- 1. DEPARTMENTS
INSERT INTO public.departments (dept_code, name, building, hod_name) VALUES
('CSE', 'Computer Science & Engineering', 'CS-Block', 'Dr. Rajesh Raman'),
('IT', 'Information Technology', 'IT-Block', 'Prof. Amitav Sen'),
('MECH', 'Mechanical Engineering', 'ME-Block', 'Dr. K. V. Narayana'),
('DE', 'Design Engineering & IoT', 'DE-Block', 'Dr. Shalini Deshmukh'),
('CIVIL', 'Civil Engineering', 'CV-Block', 'Dr. Hariprasad Varma'),
('EEE', 'Electrical & Electronics Engineering', 'EE-Block', 'Dr. Venkatachalam P.'),
('ADMIN', 'Central Administration & Student Welfare', 'Admin-Block', 'Dr. Sudhir B. Joshi')
ON CONFLICT (dept_code) DO NOTHING;

-- 2. STAFF MEMBERS (20 Faculty and Academic Officers)
INSERT INTO public.staff (staff_id, password, full_name, department, designation, email, phone, cabin_location, specialization, experience_years, office_hours) VALUES
('STF101', 'staff@123', 'Dr. Rajesh Raman', 'CSE', 'Professor & HOD', 'rajesh.raman@college.edu', '+91-9840112233', 'CS-Block Room 301', 'Deep Learning & AI', 18, '02:00 PM - 04:00 PM (Mon-Wed)'),
('STF102', 'staff@123', 'Dr. Sunita Kulkarni', 'CSE', 'Associate Professor', 'sunita.kulkarni@college.edu', '+91-9840112234', 'CS-Block Room 305', 'Distributed Cloud Systems', 12, '10:00 AM - 12:00 PM (Tue-Thu)'),
('STF103', 'staff@123', 'Prof. Vikram Saxena', 'CSE', 'Assistant Professor', 'vikram.saxena@college.edu', '+91-9840112235', 'CS-Block Room 208', 'Database Management Systems', 7, '03:00 PM - 05:00 PM (Mon-Fri)'),
('STF104', 'staff@123', 'Er. Ananya Sen', 'CSE', 'Senior Lab Instructor', 'ananya.sen@college.edu', '+91-9840112236', 'CS-Lab 404', 'AI & Robotics Lab', 6, '09:00 AM - 05:00 PM (Mon-Fri)'),
('STF105', 'staff@123', 'Prof. Amitav Sen', 'IT', 'Professor & HOD', 'amitav.sen@college.edu', '+91-9840223344', 'IT-Block Room 201', 'Cloud Infrastructure & DevOps', 16, '01:00 PM - 03:00 PM (Tue-Thu)'),
('STF106', 'staff@123', 'Dr. Radhika Menon', 'IT', 'Associate Professor', 'radhika.menon@college.edu', '+91-9840223345', 'IT-Block Room 204', 'Natural Language Processing', 11, '11:00 AM - 01:00 PM (Mon-Wed)'),
('STF107', 'staff@123', 'Prof. Tarun Bansal', 'IT', 'Assistant Professor', 'tarun.bansal@college.edu', '+91-9840223346', 'IT-Block Room 212', 'Full Stack Web & Mobile', 5, '02:00 PM - 04:00 PM (Wed-Fri)'),
('STF108', 'staff@123', 'Dr. K. V. Narayana', 'MECH', 'Professor & HOD', 'kv.narayana@college.edu', '+91-9840334455', 'ME-Block Room 101', 'Robotics & Thermal Dynamics', 20, '02:30 PM - 04:30 PM (Mon-Thu)'),
('STF109', 'staff@123', 'Prof. Deepak Chawla', 'MECH', 'Assistant Professor', 'deepak.chawla@college.edu', '+91-9840334456', 'ME-Block Room 108', 'CAD/CAM & Finite Element Analysis', 8, '10:00 AM - 12:00 PM (Tue-Fri)'),
('STF110', 'staff@123', 'Er. Ramesh Iyer', 'MECH', 'Workshop Superintendent', 'ramesh.iyer@college.edu', '+91-9840334457', 'Central Workshop Bay 2', 'Manufacturing & CNC', 14, '09:00 AM - 04:30 PM (Mon-Fri)'),
('STF111', 'staff@123', 'Dr. Shalini Deshmukh', 'DE', 'Professor & HOD', 'shalini.deshmukh@college.edu', '+91-9840445566', 'DE-Block Room 401', 'Design Thinking & Human Factors', 15, '02:00 PM - 04:00 PM (Mon-Wed)'),
('STF112', 'staff@123', 'Prof. Nikhil Bansal', 'DE', 'Assistant Professor', 'nikhil.bansal@college.edu', '+91-9840445567', 'DE-Block Room 405', 'Rapid Prototyping & 3D Modeling', 6, '11:30 AM - 01:30 PM (Tue-Thu)'),
('STF113', 'staff@123', 'Dr. Hariprasad Varma', 'CIVIL', 'Professor & HOD', 'hariprasad.varma@college.edu', '+91-9840556677', 'CV-Block Room 102', 'Structural Earthquake Dynamics', 19, '01:00 PM - 03:00 PM (Mon-Fri)'),
('STF114', 'staff@123', 'Prof. Geetha Krishnan', 'CIVIL', 'Associate Professor', 'geetha.krishnan@college.edu', '+91-9840556678', 'CV-Block Room 107', 'Geotechnical & GIS Engineering', 13, '10:00 AM - 12:00 PM (Wed-Fri)'),
('STF115', 'staff@123', 'Dr. Venkatachalam P.', 'EEE', 'Professor & HOD', 'venkat.p@college.edu', '+91-9840667788', 'EE-Block Room 201', 'Smart Grid & Renewable Energy', 17, '02:00 PM - 04:00 PM (Mon-Thu)'),
('STF116', 'staff@123', 'Prof. Archana Nambiar', 'EEE', 'Assistant Professor', 'archana.nambiar@college.edu', '+91-9840667789', 'EE-Block Room 206', 'Power Electronics & EV Drives', 9, '11:00 AM - 01:00 PM (Tue-Fri)'),
('STF117', 'staff@123', 'Dr. Sudhir B. Joshi', 'ADMIN', 'Dean of Academics', 'dean.academics@college.edu', '+91-9840778899', 'Admin Block Room 102', 'Curriculum & Academic Standards', 22, '03:00 PM - 05:00 PM (Daily)'),
('STF118', 'staff@123', 'Prof. Anita Roy', 'ADMIN', 'Dean of Student Affairs', 'dean.students@college.edu', '+91-9840778800', 'Admin Block Room 105', 'Student Grievance & Welfare', 16, '02:00 PM - 04:30 PM (Daily)'),
('STF119', 'staff@123', 'Mr. C. K. Narayanan', 'ADMIN', 'Controller of Examinations', 'coe@college.edu', '+91-9840778811', 'Exam Cell Room 10', 'Examinations & Transcripts', 21, '10:00 AM - 01:00 PM (Daily)'),
('STF120', 'staff@123', 'Mrs. Sumathi Sundaram', 'ADMIN', 'Finance & Accounts Officer', 'finance@college.edu', '+91-9840778822', 'Accounts Section Counter 1', 'Fee Clearance & Scholarships', 15, '09:30 AM - 04:00 PM (Mon-Fri)')
ON CONFLICT (staff_id) DO NOTHING;

-- 3. STUDENTS (All 20 students from user prompt Table 1)
INSERT INTO public.students (student_id, password, full_name, department, email, cgpa, phone, semester, year, attendance_pct, fee_balance, fee_status, digital_twin_score) VALUES
('23331a42001', 'student@123', 'Aarav Sharma', 'CSE', 'aarav.sharma1@college.edu', 8.74, '+91-9874523101', 8, 4, 87.4, 12500.00, 'Pending', 94),
('23331a42002', 'student@123', 'Priya Patel', 'IT', 'priya.patel2@college.edu', 9.12, '+91-8745129630', 8, 4, 91.8, 0.00, 'Paid', 98),
('23331a42003', 'student@123', 'Rohan Reddy', 'MECH', 'rohan.reddy3@college.edu', 7.45, '+91-7896541230', 8, 4, 78.2, 18500.00, 'Pending', 82),
('23331a42004', 'student@123', 'Sneha Nair', 'DE', 'sneha.nair4@college.edu', 8.89, '+91-9658741230', 8, 4, 89.0, 5000.00, 'Partial', 91),
('23331a42005', 'student@123', 'Vikram Gupta', 'CIVIL', 'vikram.gupta5@college.edu', 6.82, '+91-8521479630', 8, 4, 71.5, 22000.00, 'Pending', 70),
('23331a42006', 'student@123', 'Ananya Rao', 'EEE', 'ananya.rao6@college.edu', 9.40, '+91-7412589630', 8, 4, 94.6, 0.00, 'Paid', 99),
('23331a42007', 'student@123', 'Amit Singh', 'CSE', 'amit.singh7@college.edu', 7.91, '+91-9123456780', 8, 4, 82.3, 12500.00, 'Pending', 85),
('23331a42008', 'student@123', 'Karthik Verma', 'IT', 'karthik.verma8@college.edu', 8.15, '+91-8965412307', 8, 4, 85.0, 0.00, 'Paid', 88),
('23331a42009', 'student@123', 'Pooja Joshi', 'MECH', 'pooja.joshi9@college.edu', 7.20, '+91-7854123690', 8, 4, 76.5, 14000.00, 'Pending', 79),
('23331a42010', 'student@123', 'Rahul Mishra', 'CIVIL', 'rahul.mishra10@college.edu', 8.05, '+91-6301245789', 8, 4, 83.1, 7500.00, 'Partial', 86),
('23331a42011', 'student@123', 'Divya Kumar', 'EEE', 'divya.kumar11@college.edu', 8.90, '+91-9988776655', 8, 4, 90.2, 0.00, 'Paid', 93),
('23331a42012', 'student@123', 'Suresh Das', 'DE', 'suresh.das12@college.edu', 6.75, '+91-9123487650', 8, 4, 73.0, 25000.00, 'Pending', 68),
('23331a42013', 'student@123', 'Meera Kulkarni', 'CSE', 'meera.kulkarni13@college.edu', 9.60, '+91-9456712340', 8, 4, 96.5, 0.00, 'Paid', 100),
('23331a42014', 'student@123', 'Arjun Chatterjee', 'IT', 'arjun.chatterjee14@college.edu', 7.80, '+91-9876123450', 8, 4, 80.4, 10000.00, 'Pending', 84),
('23331a42015', 'student@123', 'Neha Verma', 'MECH', 'neha.verma15@college.edu', 8.34, '+91-9345678120', 8, 4, 86.8, 0.00, 'Paid', 89),
('23331a42016', 'student@123', 'Manish Reddy', 'CIVIL', 'manish.reddy16@college.edu', 6.95, '+91-9845123456', 8, 4, 74.2, 19500.00, 'Pending', 72),
('23331a42017', 'student@123', 'Kavya Iyer', 'EEE', 'kavya.iyer17@college.edu', 9.18, '+91-9745123456', 8, 4, 93.1, 0.00, 'Paid', 97),
('23331a42018', 'student@123', 'Ravi Singh', 'CSE', 'ravi.singh18@college.edu', 8.42, '+91-9645123456', 8, 4, 86.0, 6000.00, 'Partial', 90),
('23331a42019', 'student@123', 'Swati Gupta', 'DE', 'swati.gupta19@college.edu', 7.65, '+91-9545123456', 8, 4, 79.5, 12500.00, 'Pending', 81),
('23331a42020', 'student@123', 'Aditi Sharma', 'IT', 'aditi.sharma20@college.edu', 9.05, '+91-9445123456', 8, 4, 92.3, 0.00, 'Paid', 96)
ON CONFLICT (student_id) DO NOTHING;

-- 4. SUBJECTS
INSERT INTO public.subjects (subject_code, name, department, semester, credits, faculty_id, faculty_name, room) VALUES
('CS801', 'Deep Learning Architecture', 'CSE', 8, 4, 'STF101', 'Dr. Rajesh Raman', 'Lab 404'),
('CS802', 'Natural Language Processing', 'CSE', 8, 4, 'STF106', 'Dr. Radhika Menon', 'Room 304'),
('CS803', 'Database Management Systems', 'CSE', 8, 3, 'STF103', 'Prof. Vikram Saxena', 'Room CS-204'),
('CS804', 'Distributed Cloud Systems', 'CSE', 8, 4, 'STF102', 'Dr. Sunita Kulkarni', 'Room 305'),
('IT801', 'Cloud Infrastructure & DevOps', 'IT', 8, 4, 'STF105', 'Prof. Amitav Sen', 'IT Lab 202'),
('IT802', 'Modern Web Architectures', 'IT', 8, 3, 'STF107', 'Prof. Tarun Bansal', 'Room IT-212'),
('ME801', 'Robotics & Automation', 'MECH', 8, 4, 'STF108', 'Dr. K. V. Narayana', 'ME Lab 105'),
('ME802', 'Finite Element Analysis', 'MECH', 8, 4, 'STF109', 'Prof. Deepak Chawla', 'CAD Lab Bay 1'),
('DE801', 'IoT & Sensor Systems Design', 'DE', 8, 4, 'STF111', 'Dr. Shalini Deshmukh', 'DE Lab 402'),
('CV801', 'Advanced Structural Dynamics', 'CIVIL', 8, 4, 'STF113', 'Dr. Hariprasad Varma', 'CV Room 102'),
('EE801', 'Smart Grid Power Systems', 'EEE', 8, 4, 'STF115', 'Dr. Venkatachalam P.', 'EE Room 201')
ON CONFLICT (subject_code) DO NOTHING;

-- 5. STUDENT SUBJECT ATTENDANCE (Sample for Aarav Sharma & peers)
INSERT INTO public.student_attendance (student_id, subject_code, subject_name, attended_sessions, total_sessions, percentage, status) VALUES
('23331a42001', 'CS801', 'Deep Learning Architecture', 38, 41, 92.68, 'Good'),
('23331a42001', 'CS802', 'Natural Language Processing', 34, 38, 89.47, 'Good'),
('23331a42001', 'CS803', 'Database Management Systems', 28, 36, 77.78, 'Warning'),
('23331a42001', 'CS804', 'Distributed Cloud Systems', 32, 35, 91.43, 'Good'),
('23331a42002', 'IT801', 'Cloud Infrastructure & DevOps', 39, 40, 97.50, 'Good'),
('23331a42002', 'IT802', 'Modern Web Architectures', 36, 38, 94.74, 'Good'),
('23331a42005', 'CV801', 'Advanced Structural Dynamics', 25, 36, 69.44, 'Critical');

-- 6. FEE RECORDS
INSERT INTO public.fee_records (student_id, semester, academic_year, tuition_fee, lab_fee, exam_fee, paid_amount, balance_amount, status, due_date) VALUES
('23331a42001', 8, '2025-2026', 12500.00, 5000.00, 2500.00, 7500.00, 12500.00, 'Pending', '2026-11-15'),
('23331a42002', 8, '2025-2026', 12500.00, 5000.00, 2500.00, 20000.00, 0.00, 'Paid', '2026-11-15'),
('23331a42003', 8, '2025-2026', 12500.00, 5000.00, 2500.00, 1500.00, 18500.00, 'Pending', '2026-11-15'),
('23331a42006', 8, '2025-2026', 12500.00, 5000.00, 2500.00, 20000.00, 0.00, 'Paid', '2026-11-15');

-- 7. CERTIFICATE REQUESTS
INSERT INTO public.certificate_requests (request_id, student_id, student_name, certificate_type, status, applied_date, purpose, remarks) VALUES
('REQ-8841', '23331a42001', 'Aarav Sharma', 'Bonafide Certificate (Passport / Visa)', 'In Review', CURRENT_DATE - 1, 'Passport Renewal Application', 'Dean verification in progress'),
('REQ-7729', '23331a42001', 'Aarav Sharma', 'Grade Verification Report', 'Pending OCR', CURRENT_DATE - 3, 'Higher Studies Application', 'Pending automated document validation'),
('REQ-9210', '23331a42002', 'Priya Patel', 'Provisional Degree Certificate', 'Approved', CURRENT_DATE - 5, 'Campus Placement Document Check', 'Digitally signed by Dean of Academics'),
('REQ-9450', '23331a42006', 'Ananya Rao', 'Course Completion Letter', 'Approved', CURRENT_DATE - 7, 'Internship Verification', 'Ready for download');

-- 8. ACTIVITY LOGS
INSERT INTO public.activity_logs (student_id, title, description, time_label, icon, icon_color) VALUES
('23331a42001', 'Biometric Attendance Recorded', 'Deep Learning Lab 404 • Console RFID check verified', 'Today, 10:42 AM', 'check_circle', 'emerald'),
('23331a42001', 'Bonafide Certificate In Review', 'Passport Application • Dean verification in progress', 'Yesterday', 'assignment_turned_in', 'purple'),
('23331a42001', 'Fee Receipt #REC-8841 Generated', 'Transport installment cleared • Stored in Document Vault', '3 days ago', 'receipt_long', 'blue');

-- 9. CHATBOT KNOWLEDGE BASE
INSERT INTO public.knowledge_base (category, question, answer, keywords) VALUES
('Attendance', 'What is the minimum attendance requirement?', 'The university requires a minimum of 75% overall attendance in each registered course to be eligible for end-semester examinations. Students between 65% and 74.9% with valid medical certificates may apply for condonation. Students below 65% face course detention.', ARRAY['attendance', 'cutoff', 'minimum', 'detention', 'condonation', 'eligibility', '75']),
('Attendance', 'Can I skip DBMS today?', 'Your current attendance in Database Management Systems is 77.8% (28/36 sessions). Missing a lecture will drop you to 75.6%, which is critically close to the 75% cutoff. We strongly advise attending the next 2 lectures to reach the 80% safe zone.', ARRAY['skip', 'dbms', 'miss', 'class', 'database']),
('Fees', 'What is the tuition fee deadline and payment process?', 'The deadline for Semester 8 tuition fees (₹12,500) is November 15. You can pay directly online via UPI, Net Banking, or Credit/Debit card through the portal "Fees" tab. Late payment incurs a ₹500 weekly penalty and registration hold.', ARRAY['fee', 'tuition', 'deadline', 'pay', 'penalty', 'balance']),
('Certificates', 'How do I apply for a Bonafide Certificate?', 'Go to the "Certificates" tab in your portal, choose "Bonafide Certificate (Passport/Visa)", upload any optional supporting letter, and click Submit. Normal turnaround time is 24 to 48 hours. You can download the digitally signed PDF once approved.', ARRAY['bonafide', 'certificate', 'passport', 'visa', 'apply']),
('Faculty', 'Who is the HOD of Computer Science (CSE)?', 'The Head of the Department of Computer Science & Engineering is Dr. Rajesh Raman. His office is located in CS-Block Room 301, and his office hours are Mon-Wed 2:00 PM to 4:00 PM (Email: rajesh.raman@college.edu).', ARRAY['hod', 'cse', 'computer science', 'rajesh', 'raman', 'cabin']),
('Faculty', 'Who is the HOD of Information Technology (IT)?', 'The HOD of Information Technology is Prof. Amitav Sen. His office is located in IT-Block Room 201, and his office hours are Tue-Thu 1:00 PM to 3:00 PM (Email: amitav.sen@college.edu).', ARRAY['hod', 'it', 'information technology', 'amitav', 'sen']),
('Faculty', 'Who is the Dean of Academics?', 'Dr. Sudhir B. Joshi is the Dean of Academics. His office is in Administrative Block Room 102. Office hours are daily from 3:00 PM to 5:00 PM (Email: dean.academics@college.edu).', ARRAY['dean', 'academics', 'sudhir', 'joshi', 'admin']),
('Exams', 'When are the Semester 8 midterm and end-term exams?', 'Semester 8 Midterms begin December 02, 2024. End-semester theory examinations are scheduled from April 14, 2025 to April 28, 2025. Hall tickets will be released 7 days before exams for students with clear fee and attendance dues.', ARRAY['exam', 'midterm', 'schedule', 'date', 'hall ticket', 'end-semester']),
('Digital Twin', 'What does the Digital Twin Health Score mean?', 'Your Digital Twin score (e.g. 94/100) is a predictive composite metric calculated from your lecture attendance consistency, continuous internal assessment (CIA) grades, fee clearance timeliness, and lab milestones. Scores above 85 indicate optimal graduation pace.', ARRAY['digital twin', 'twin', 'health', 'score', 'pace', 'prediction']);
